### ISSUE TITLE
Chapter 08 - sniffer rlua issue

### ISSUE THREAD

**Issue by srufle** [PacktPublishing/Hands-On-Concurrency-with-Rust#1]
I think its having an issue with rlua. I tried upgrading to the latest, but rlua had api breaking changes in the latest 0.17.x version.

I am on Ubuntu 18.04 running cargo 1.45.1 (f242df6ed 2020-07-22) stable
`cargo build --release`

Then run 
`RUST_BACKTRACE=full ./target/debug/sniffer eno1 examples/pulse.lua `

``` text 
thread 'main' panicked at 'attempted to leave type `[closure@/home/srufle/.cargo/registry/src/github.com-1ecc6299db9ec823/rlua-0.13.0/src/util.rs:238:35: 240:6 s:&&str]` uninitialized, which is invalid', /home/srufle/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libcore/mem/mod.rs:655:5
stack backtrace:
   0:     0x55fc281e65b5 - backtrace::backtrace::libunwind::trace::hc5f524da7fd1bf36
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1:     0x55fc281e65b5 - backtrace::backtrace::trace_unsynchronized::hd11faf0c738b3334
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2:     0x55fc281e65b5 - std::sys_common::backtrace::_print_fmt::h178f112e0f8e4683
                               at src/libstd/sys_common/backtrace.rs:78
   3:     0x55fc281e65b5 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hb0a22bd860f1c150
                               at src/libstd/sys_common/backtrace.rs:59
   4:     0x55fc28205acc - core::fmt::write::haef1c8ec4be874ff
                               at src/libcore/fmt/mod.rs:1076
   5:     0x55fc281e43e3 - std::io::Write::write_fmt::h076fbfae51d9d5ec
                               at src/libstd/io/mod.rs:1537
   6:     0x55fc281e8d00 - std::sys_common::backtrace::_print::he39ed648b9862ab3
                               at src/libstd/sys_common/backtrace.rs:62
   7:     0x55fc281e8d00 - std::sys_common::backtrace::print::h160b78e9d6f039e6
                               at src/libstd/sys_common/backtrace.rs:49
   8:     0x55fc281e8d00 - std::panicking::default_hook::{{closure}}::h585caa318b2cae3c
                               at src/libstd/panicking.rs:198
   9:     0x55fc281e8a4c - std::panicking::default_hook::h41b5eb8bbd1a0d2c
                               at src/libstd/panicking.rs:218
  10:     0x55fc281e9337 - std::panicking::rust_panic_with_hook::h8dd35d3cd11497d7
                               at src/libstd/panicking.rs:486
  11:     0x55fc281e8f3b - rust_begin_unwind
                               at src/libstd/panicking.rs:388
  12:     0x55fc28204ed1 - core::panicking::panic_fmt::hdf118db3fcd2d481
                               at src/libcore/panicking.rs:101
  13:     0x55fc28204e1d - core::panicking::panic::h1ea08ce5a03d11a8
                               at src/libcore/panicking.rs:56
  14:     0x55fc280b7e06 - core::mem::uninitialized::h9aefc5bbfdccb745
                               at /home/srufle/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libcore/mem/mod.rs:655
  15:     0x55fc280b7e06 - rlua::util::protect_lua_call::do_call::h70fd3734b89c3e57
                               at /home/srufle/.cargo/registry/src/github.com-1ecc6299db9ec823/rlua-0.13.0/src/util.rs:129
  16:     0x55fc280d925b - luaD_precall
                               at lua/ldo.c:434
  17:     0x55fc280d9633 - luaD_call
                               at lua/ldo.c:498
  18:     0x55fc280d96a1 - luaD_callnoyield
                               at lua/ldo.c:509
  19:     0x55fc280cfcc6 - f_call
                               at lua/lapi.c:942
  20:     0x55fc280d8584 - luaD_rawrunprotected
                               at lua/ldo.c:142
  21:     0x55fc280da024 - luaD_pcall
                               at lua/ldo.c:729
  22:     0x55fc280cfee5 - lua_pcallk
                               at lua/lapi.c:968
  23:     0x55fc280c1fc2 - rlua::ffi::lua_pcall::heabdcaf4d9cdab70
                               at /home/srufle/.cargo/registry/src/github.com-1ecc6299db9ec823/rlua-0.13.0/src/ffi.rs:310
  24:     0x55fc280b776a - rlua::util::protect_lua_call::h12753174a72de06a
                               at /home/srufle/.cargo/registry/src/github.com-1ecc6299db9ec823/rlua-0.13.0/src/util.rs:161
  25:     0x55fc280b8609 - rlua::util::push_string::hd7724063365625ef
                               at /home/srufle/.cargo/registry/src/github.com-1ecc6299db9ec823/rlua-0.13.0/src/util.rs:238
  26:     0x55fc280bcea3 - rlua::lua::Lua::create_lua::{{closure}}::hc5c2e37f32c751a0
                               at /home/srufle/.cargo/registry/src/github.com-1ecc6299db9ec823/rlua-0.13.0/src/lua.rs:955
  27:     0x55fc280b6333 - rlua::util::stack_guard::h4eed03e50326eebc
                               at /home/srufle/.cargo/registry/src/github.com-1ecc6299db9ec823/rlua-0.13.0/src/util.rs:44
  28:     0x55fc280bcc7b - rlua::lua::Lua::create_lua::h94930a9521bedfb9
                               at /home/srufle/.cargo/registry/src/github.com-1ecc6299db9ec823/rlua-0.13.0/src/lua.rs:926
  29:     0x55fc280bb2cf - rlua::lua::Lua::new::h0bbfb3583a5787fb
                               at /home/srufle/.cargo/registry/src/github.com-1ecc6299db9ec823/rlua-0.13.0/src/lua.rs:75
  30:     0x55fc280a46e7 - sniffer::main::h1903b84514d42427
                               at src/bin/sniffer.rs:87
  31:     0x55fc2809eeab - std::rt::lang_start::{{closure}}::h2876a6e9cb2b28e8
                               at /home/srufle/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/rt.rs:67
  32:     0x55fc281e97c8 - std::rt::lang_start_internal::{{closure}}::hfca5b90b4b1ebb0e
                               at src/libstd/rt.rs:52
  33:     0x55fc281e97c8 - std::panicking::try::do_call::hfc9c880ab92e6248
                               at src/libstd/panicking.rs:297
  34:     0x55fc281e97c8 - std::panicking::try::h2ed6f772c4dd6273
                               at src/libstd/panicking.rs:274
  35:     0x55fc281e97c8 - std::panic::catch_unwind::hc6028b0fc71765c5
                               at src/libstd/panic.rs:394
  36:     0x55fc281e97c8 - std::rt::lang_start_internal::heb6c9d57f3355ded
                               at src/libstd/rt.rs:51
  37:     0x55fc2809ee87 - std::rt::lang_start::hf32af37166c058cc
                               at /home/srufle/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/rt.rs:67
  38:     0x55fc280a545a - main
  39:     0x7f4d289f0b97 - __libc_start_main
  40:     0x55fc2809571a - _start
  41:                0x0 - <unknown>
```

**Comment by blt** [comment]
Hi @srufle, interesting. The relevant part of the traceback looks to be:

> 'attempted to leave type `[closure@/home/srufle/.cargo/registry/src/github.com-1ecc6299db9ec823/rlua-0.13.0/src/util.rs:238:35: 240:6 s:&&str]` uninitialized, which is invalid'

Can you confirm that your Rust version is the one listed in the book? I don't have a copy to reference but I believe the version is specified in the first chapter or so? My recollection is that `rlua` is temperamental about the Rust version it builds with, somewhat less touchy about the system compilers. It, sort of necessarily, does unsafe things internally and it looks like you've hit a memory error after the FFI boundary is crossed.

**Comment by blt** [comment]
Hmm. Well, scanning my digital copy of the book it appears in the first chapter we only listed 'stable' as the Rust version. Unfortunate. I recall using something around Rust 1.17. If it were me, my next steps would be to:

* hollow out the lua script and see if I can't get a smaller program that does not cause the crash,
* compile with Rust 1.17-ish or
* maybe try to upgrade `rlua`. 

As you say, the API for `rlua` changed but you could be more sure of support from that project with a current version. I haven't done embedded lua in Rust for a year plus at this point, so I'm not sure how difficult that upgrade path is.
